_wandb:
    value:
        cli_version: 0.21.1
        e:
            fx30i3nza4w3n63o1520r2clwgvj2ms8:
                args:
                    - --data_roots
                    - /Volumes/1TBSSD/MineRL/MineRLNavigate-v0
                    - /Volumes/1TBSSD/MineRL/MineRLTreechop-v1
                    - /Volumes/1TBSSD/MineRL/MineRLNavigateExtreme-v0
                    - /Volumes/1TBSSD/MineRL/MineRLObtainDiamond-v0
                    - --save_ckpt
                    - tokenizer_ms_vqvae2.pt
                codePath: train_tokenizer.py
                codePathLocal: train_tokenizer.py
                email: max.gluhovskoi@gmail.com
                executable: /Users/maximgluhovskoi/opt/anaconda3/envs/py312/bin/python
                git:
                    commit: 0265ac1619b77ac87e97e91b38a53792bfc48c0a
                    remote: https://github.com/MaximGluhovskoi/cmu-10X23.git
                host: Maxims-MacBook-Pro-418.local
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/maximgluhovskoi/Desktop/Desktop_sub/10723/project/cmu-10X23/train_tokenizer.py
                python: CPython 3.12.11
                root: /Users/maximgluhovskoi/Desktop/Desktop_sub/10723/project/cmu-10X23
                startedAt: "2025-12-08T17:56:59.694033Z"
                writerId: fx30i3nza4w3n63o1520r2clwgvj2ms8
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.11
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": darwin-arm64
base_channels:
    value: 64
batch_size:
    value: 32
epochs:
    value: 50
latent_dim:
    value: 128
num_embeddings:
    value: 1024
num_frames:
    value: 32
